apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-app
    appstudio.openshift.io/component: test-app-devfile-sample-go-basic-itth-sample
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-app-devfile-sample-go-basic-itth-sample
  namespace: gazarenk-tenant
spec:
  url: https://github.com/devfile-samples/devfile-sample-go-basic
