apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-app-devfile-sample-go-basic-itth-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-app-devfile-sample-go-basic-itth-sample
    app.kubernetes.io/part-of: test-app
  name: test-app-devfile-sample-go-basic-itth-sample
  namespace: gazarenk-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-app-devfile-sample-go-basic-itth-sample
    weight: 100
status: {}
